# Generated by Django 5.2.3 on 2025-06-16 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_property_address_remove_property_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='pictures',
        ),
        migrations.AddField(
            model_name='property',
            name='property_video',
            field=models.FileField(blank=True, help_text='Optional video tour of the property', null=True, upload_to='property_videos/'),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
        ),
    ]
